version: '3.8'
services:
  ui:
    image: skyvernai/skyvern-ui:latest
    environment:
      - NEXT_PUBLIC_API_URL=http://${DOMAIN:-localhost}:8000
      - NEXT_PUBLIC_WS_URL=ws://${DOMAIN:-localhost}:8000
    ports:
      - "8080:3000"
    networks:
      - coolify

  api:
    image: skyvernai/skyvern-api:latest
    environment:
      - LLM_KEY=${LLM_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Use Coolify's database connection string
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    ports:
      - "8000:8000"
    networks:
      - coolify

networks:
  coolify:
    external: true
