services:
  skyvern:
    image: public.ecr.aws/skyvern/skyvern:latest
    restart: on-failure
    ports:
      - 8009:8000  # Changed port to avoid conflict
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./log:/data/log
      - ./.streamlit:/app/.streamlit
    environment:
      - DATABASE_STRING=${DATABASE_URL}  # Using Coolify's database URL
      - BROWSER_TYPE=chromium-headful
      - ENABLE_OPENAI=false
      - ENABLE_ANTHROPIC=true
      - ENABLE_AZURE=false
      - ENABLE_BEDROCK=false
      - ENABLE_GEMINI=false
      - ENABLE_NOVITA=false
      - LLM_KEY=ANTHROPIC_CLAUDE3.5_SONNET
      - SECONDARY_LLM_KEY=ANTHROPIC_CLAUDE3.5_SONNET
    healthcheck:
      test: ["CMD", "test", "-f", "/app/.streamlit/secrets.toml"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern-ui:
    image: public.ecr.aws/skyvern/skyvern-ui:latest
    restart: on-failure
    ports:
      - 8081:8080  # Changed port to avoid conflict
      - 9091:9090  # Changed port to avoid conflict
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./.streamlit:/app/.streamlit
    environment:
      # if you want to run skyvern on a remote server,
      # you need to change the host in VITE_WSS_BASE_URL and VITE_API_BASE_URL to match your server ip
      # If you're self-hosting this behind a dns, you'll want to set:
      #   A route for the API: api.yourdomain.com -> localhost:8000
      #   A route for the UI: yourdomain.com -> localhost:8080
      #   A route for the artifact API: artifact.yourdomain.com -> localhost:9090 (maybe not needed)
      #   - VITE_ARTIFACT_API_BASE_URL=http://localhost:9090
      #   - VITE_API_BASE_URL=http://localhost:8000/api/v1
      - VITE_WSS_BASE_URL=ws://${DOMAIN:-localhost}:8009/api/v1
      - VITE_API_BASE_URL=http://${DOMAIN:-localhost}:8009/api/v1
    networks:
      - coolify
    depends_on:
      skyvern:
        condition: service_healthy

networks:
  coolify:
    external: true