version: '3.8'
services:
  skyvern:
    image: public.ecr.aws/skyvern/skyvern:latest
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - BROWSER_TYPE=chromium-headful
      - ENABLE_OPENAI=true
      - LLM_KEY=${LLM_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - coolify

  skyvern-ui:
    image: public.ecr.aws/skyvern/skyvern-ui:latest
    restart: on-failure
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - VITE_WSS_BASE_URL=ws://${DOMAIN:-localhost}:8000/api/v1
      - VITE_API_BASE_URL=http://${DOMAIN:-localhost}:8000/api/v1
    networks:
      - coolify

networks:
  coolify:
    external: true
